# Generated by Django 3.1.12 on 2021-08-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillmaster',
            fields=[
                ('skillid', models.IntegerField(primary_key=True, serialize=False)),
                ('skillname', models.CharField(max_length=30)),
                ('skilltype', models.CharField(max_length=20)),
                ('skilldescription', models.TextField()),
            ],
            options={
                'db_table': 'user_student_skillmaster',
            },
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('student_skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(null=True)),
                ('skillid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.TextField()),
                ('user_score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('question_content_id', models.IntegerField(blank=True, null=True)),
                ('assessment_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_admin.assessment_type')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.batch')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.module_level')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.student')),
            ],
        ),
    ]
