# Generated by Django 3.1.12 on 2021-08-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
        ('user_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skillid',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user_student.skillmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skills',
            name='student_id',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='user_admin.student'),
            preserve_default=False,
        ),
    ]
