# Generated by Django 3.1.12 on 2021-08-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
        ('user_student', '0004_auto_20210807_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skillid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_student.skillmaster'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.student'),
        ),
    ]
