# Generated by Django 3.1.12 on 2021-08-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0005_auto_20210807_2120'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skillmaster',
            table=None,
        ),
    ]
